# Generated by Django 4.2.4 on 2023-08-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=90)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="author/cover/%Y/%m/%d/"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("bio", models.CharField(max_length=200)),
                ("death", models.CharField(max_length=200)),
                ("date_birth", models.DateField()),
                ("date_death", models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="books/cover/%Y/%m/%d/"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="writers.author"
                    ),
                ),
            ],
        ),
    ]
