# Generated by Django 4.2.4 on 2023-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=90)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="", upload_to="author/cover/%Y/%m/%d/"
                    ),
                ),
                ("bio", models.CharField(max_length=200)),
                ("death", models.CharField(max_length=200)),
                ("date_birth", models.DateField()),
                ("date_death", models.DateField(blank=True, default=None)),
            ],
        ),
    ]
