# Generated by Django 3.2 on 2023-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_auto_20230917_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download',
            field=models.TextField(default=''),
        ),
    ]
