# Generated by Django 3.2 on 2023-10-06 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0003_book_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mini_description', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=4000)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writers.author')),
            ],
        ),
    ]
