# Generated by Django 3.2 on 2023-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0004_auto_20231005_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='mini_description',
            field=models.TextField(max_length=255),
        ),
    ]
