# Generated by Django 3.2 on 2023-10-06 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writers', '0005_alter_poem_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
