# Generated by Django 3.2 on 2023-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0008_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='author',
            name='death',
            field=models.CharField(max_length=300),
        ),
    ]
