# Generated by Django 3.2 on 2023-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0009_auto_20231115_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_book_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='is_poem_author',
            field=models.BooleanField(default=False),
        ),
    ]
